### ISSUE TITLE
revision 6a3ff018b1 (2 weeks ago) • 2018-10-26 01:30:21 -0400 breaks fcharts 0.0.9

### ISSUE THREAD

**Issue by LiveRock** [thekeenant/fcharts#22]
Flutter 0.10.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 6a3ff018b1 (2 weeks ago) • 2018-10-26 01:30:21 -0400

Compiler message:
file:///dev/pub.dartlang.org/fcharts-0.0.9/lib/src/bar/data.dart:14:7: Error: Inferred type argument '#lib1::ChartDrawable<dynamic, #lib1::ChartTouch>'
violates the corresponding type variable bound of 'ChartData' in the supertype 'ChartData' of class 'BarGraphData'.
Try specifying type arguments explicitly so that they conform to the bounds.
class BarGraphData implements ChartData {
      ^
file:///dev/flutter/.pub-cache/hosted/pub.dartlang.org/fcharts-0.0.9/lib/src/chart_data.dart:4:26: Context: Bound of this variable is violated.
abstract class ChartData<T extends ChartDrawable<T, ChartTouch>> {
                         ^
Compiler terminated unexpectedly.

Please help!

**Comment by LiveRock** [comment]
Downgrade Flutter to v0.10.1 resolve the issue but for long term, I think should should future version versions of Flutter. Thanks!

**Comment by thekeenant** [comment]
Thanks for reporting!

Fixed with f996a1ed6141ae37d19df17205600abe70977057
