### ISSUE TITLE
Control of chart animation

### ISSUE THREAD

**Issue by rubberbird** [thekeenant/fcharts#27]
It would be great to have the ability to control the animation of the data being written to the charts. For example a line graph that would draw temperature in realtime while the use is watching it.

**Comment by thekeenant** [comment]
If you are using a stateful flutter widget, you should be able to maintain the data in your state and update it inside flutter's `setState`. The chart should animate to the new values you provide. Is this what you mean?

**Comment by Nazacheres** [comment]
Hello, @thekeenant, first of all, thank you for your work!
Probably not what the author meant, but let me elaborate on this issue: **is there a way to control animation duration?** 
Let's say I use LineChart, and I feed new data every second. I want the animation to go slow, and smooth so it doesn't seem like it stops between states, for that I would need to control animation time.

**Comment by Nazacheres** [comment]
@thekeenant Just to clarify, I mean animation which happens on changing DoubleSpan.
