### ISSUE TITLE
Is it possible to draw value label on point with line chart?

### ISSUE THREAD

**Issue by fengqiangboy** [thekeenant/fcharts#29]
Is it possible to draw value label on point with line chart?

Mark point with value label

**Comment by thekeenant** [comment]
No, there is no API available for labeling the points in this library unfortunately. However, you could do something like [this](https://gist.github.com/thekeenant/fb83599813df95787b56fc2e4dfd6b5d), adapted from the city example. See `LabeledMarkerShape`. This is hacky and I would *not* recommend it for obvious reasons (counter is outside of the state, no guarantee it will be indexed properly, and this method of drawing text may be out of bounds in some cases). I do welcome PRs to support drawing the value label.

![image](https://user-images.githubusercontent.com/1189775/54662104-10df4f00-4a9a-11e9-84df-a9f7c46946ca.png)

**Comment by RedSevenMale** [comment]
how can i find LabeledMarkerShape?i want to get this effect above  adapted from the city example

**Comment by thekeenant** [comment]
@RedSevenMale It's in the Gist I linked earlier: https://gist.github.com/thekeenant/fb83599813df95787b56fc2e4dfd6b5d

It is a custom `MarkerShape` I made for the purpose of the demonstration. But I would recommend checking out [charts_flutter](https://pub.dartlang.org/packages/charts_flutter), they might have a solution that isn't so hacky.
